// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordiskaPortal.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NordiskaPortal.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007090520_ProtectPersonalNumber")]
    partial class ProtectPersonalNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NordiskaPortal.API.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            AccountNumber = "NKM-10001",
                            AccountType = "CHECKING",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transaktionskonto",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("d0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            AccountNumber = "NKM-10002",
                            AccountType = "SAVINGS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sparkonto",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("d0000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.FaqEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("FaqEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000001"),
                            Answer = "Gå till Dashboard och välj Skapa nytt sparkonto. Ge kontot ett namn och välj ikon och färg, så skapas det direkt.",
                            Category = "Konto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "öppna konto, öppna sparkonto, öppna nytt konto, nytt konto, nytt sparkonto, skapa konto, skapa sparkonto, skapa nytt konto, starta sparkonto, ansöka konto",
                            Question = "Hur öppnar jag ett nytt sparkonto?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000002"),
                            Answer = "Ja, du kan skapa flera sparkonton och döpa dem efter vad du sparar till, till exempel Resekassa. Alla syns på din Dashboard.",
                            Category = "Konto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "flera konton, flera sparkonton, fler konton, fler sparkonton, ett till konto, ytterligare konto, kontonamn, namnge konto, döpa konto, antal konton",
                            Question = "Kan jag ha flera sparkonton?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000003"),
                            Answer = "Ta ut hela saldot och kontakta sedan kundtjänst för att avsluta kontot.",
                            Category = "Konto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "avsluta konto, avsluta sparkonto, stänga konto, stänga sparkonto, säga upp konto, säga upp sparkonto, ta bort konto, radera konto, lägga ner konto",
                            Question = "Hur avslutar jag mitt sparkonto?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000004"),
                            Answer = "Välj Insättning/Uttag i menyn och sedan Sätt in. Ange konto och belopp och bekräfta. Pengarna syns direkt på kontot.",
                            Category = "Insättning",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "insättning, sätta in, sätter in, sätt in, sätta in pengar, sätter in pengar, lägga in pengar, lägger in pengar, deponera, spara pengar",
                            Question = "Hur sätter jag in pengar?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000005"),
                            Answer = "Välj Insättning/Uttag i menyn och sedan Ta ut. Ange konto och belopp och bekräfta. Du kan bara ta ut pengar som finns på kontot, och saldot uppdateras direkt.",
                            Category = "Uttag",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "uttag, ta ut, tar ut, ta ut pengar, tar ut pengar, ta ut saldo, ta ut belopp, plocka ut pengar, hämta ut pengar, göra uttag, ta pengar",
                            Question = "Hur tar jag ut pengar?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000006"),
                            Answer = "Ett uttag registreras direkt och saldot på kontot uppdateras med en gång.",
                            Category = "Uttag",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "tid uttag, lång tid uttag, snabbt uttag, uttaget syns, när kommer pengarna, dröja uttag, handläggningstid",
                            Question = "Hur lång tid tar ett uttag?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000007"),
                            Answer = "Välj Insättning/Uttag i menyn och sedan Mellan konton. Välj kontot pengarna ska flyttas från och till, ange belopp och bekräfta.",
                            Category = "Överföring",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "flytta pengar, flytta mellan konton, mellan konton, överföring, överföra, överföra pengar, föra över pengar, flytta saldo, från konto till konto",
                            Question = "Hur flyttar jag pengar mellan mina konton?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000008"),
                            Answer = "Räntan beräknas dagligen och betalas ut den 31 december varje år.",
                            Category = "Ränta",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "ränta, räntan, ränteutbetalning, utbetalning ränta, räntesats, ränta procent, få ränta, när betalas ränta, ränta 31 december, räkna ränta",
                            Question = "När betalas räntan ut?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000009"),
                            Answer = "Välj Skatterapport i menyn och sedan år. Där finns underlaget för ränta och transaktioner för det året.",
                            Category = "Rapporter",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "räntebesked, årsbesked, skatterapport, skatteunderlag, skatt, deklaration, deklarera, kontrolluppgift, underlag, ladda ner rapport",
                            Question = "Var hittar jag mitt räntebesked eller årsbesked?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000010"),
                            Answer = "Under Historik i menyn ser du alla dina transaktioner och kan filtrera på konto och typ. Ett fullständigt underlag för hela året finns i Skatterapport.",
                            Category = "Rapporter",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "kontoutdrag, utdrag, transaktioner, transaktionshistorik, historik, se transaktioner, mina transaktioner, kontohistorik, händelser",
                            Question = "Hur får jag ett kontoutdrag?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000011"),
                            Answer = "Ja, dina pengar omfattas av insättningsgarantin enligt de villkor som gäller för kontot.",
                            Category = "Trygghet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "skyddade, skyddad, insättningsgaranti, garanti, trygga pengar, säkra pengar, säkerhet, riksgälden, bankkonkurs, förlora pengar",
                            Question = "Är mina pengar skyddade?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000012"),
                            Answer = "Fullständiga avtalsvillkor skickas till dig per post. Kontakta kundtjänst om du saknar dem.",
                            Category = "Villkor",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "villkor, villkoren, avtal, avtalsvillkor, kundavtal, regler, bestämmelser, kontovillkor",
                            Question = "Var hittar jag villkoren för mitt sparkonto?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000013"),
                            Answer = "Klicka på din profil uppe till höger och välj Profil och inställningar för att ändra namn och e-post.",
                            Category = "Profil",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "kontaktuppgifter, ändra e-post, byta e-post, ändra epost, e-postadress, mejl, mail, ändra namn, byta namn, profil, inställningar, uppgifter",
                            Question = "Hur ändrar jag mina kontaktuppgifter?"
                        },
                        new
                        {
                            Id = new Guid("fa000000-0000-0000-0000-000000000014"),
                            Answer = "Ring 08-123 456 78 vardagar 8-18 eller mejla hej@nordiska.se.",
                            Category = "Kontakt",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keywords = "kundtjänst, kundservice, kontakta, kontakt, ringa, telefon, telefonnummer, ring oss, mejla, support, öppettider, chatt, prata med någon",
                            Question = "Hur kontaktar jag kundtjänst?"
                        });
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("LedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deposit",
                            EntryType = "DEPOSIT",
                            TransactionId = new Guid("d0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-00000000000a"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = 3000m,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deposit",
                            EntryType = "DEPOSIT",
                            TransactionId = new Guid("d0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-00000000000b"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = -750m,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Withdrawal",
                            EntryType = "WITHDRAWAL",
                            TransactionId = new Guid("d0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-00000000000c"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Amount = 20000m,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deposit",
                            EntryType = "DEPOSIT",
                            TransactionId = new Guid("d0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-00000000000d"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deposit",
                            EntryType = "DEPOSIT",
                            TransactionId = new Guid("d0000000-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.TaxReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("NativeExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<int>("ReportYear")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaxReports");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = 5000m,
                            CompletedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "COMPLETED",
                            TransactionType = "DEPOSIT"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = 3000m,
                            CompletedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "COMPLETED",
                            TransactionType = "DEPOSIT"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Amount = 750m,
                            CompletedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "COMPLETED",
                            TransactionType = "WITHDRAWAL"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Amount = 20000m,
                            CompletedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "COMPLETED",
                            TransactionType = "DEPOSIT"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            AccountId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Amount = 5000m,
                            CompletedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "COMPLETED",
                            TransactionType = "DEPOSIT"
                        });
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalNumberHash")
                        .HasColumnType("text");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonalNumberHash")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@nordiskaportal.se",
                            FirstName = "Demo",
                            LastName = "Kund",
                            PersonalNumber = "19850615-5678",
                            PinHash = "$2b$12$Ma9ikA7xtUOXMH86.OZA7eYIEb.yDiazDkk5uu5M/4PpbuC3ORvSu",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Account", b =>
                {
                    b.HasOne("NordiskaPortal.API.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.LedgerEntry", b =>
                {
                    b.HasOne("NordiskaPortal.API.Models.Account", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NordiskaPortal.API.Models.Transaction", "Transaction")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Notification", b =>
                {
                    b.HasOne("NordiskaPortal.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.TaxReport", b =>
                {
                    b.HasOne("NordiskaPortal.API.Models.User", "User")
                        .WithMany("TaxReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Transaction", b =>
                {
                    b.HasOne("NordiskaPortal.API.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Account", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.Transaction", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("NordiskaPortal.API.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Notifications");

                    b.Navigation("TaxReports");
                });
#pragma warning restore 612, 618
        }
    }
}
