#ifndef NORDISKA_ERROR_CODES_H
#define NORDISKA_ERROR_CODES_H

typedef enum NordiskaExitCode {
    NORDISKA_EXIT_SUCCESS = 0,
    NORDISKA_EXIT_INVALID_INPUT = 1,
    NORDISKA_EXIT_FILE_ERROR = 2,
    NORDISKA_EXIT_PDF_GENERATION_ERROR = 3,
    NORDISKA_EXIT_SIGNING_ERROR = 4
} NordiskaExitCode;

#endif // NORDISKA_ERROR_CODES_H